### ISSUE TITLE
not working on iOS devices

### ISSUE THREAD

**Issue by Hina-Hussain** [fuadarradhi/datetime_setting#2]
Unhandled Exception: type 'String' is not a subtype of type 'bool' in type cast
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:41)

Getting this exception when working on ios devices.

**Comment by AshishInnovantes** [comment]
> Unhandled Exception: type 'String' is not a subtype of type 'bool' in type cast
> #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:41)
> 
> Getting this exception when working on ios devices.

I am having the same issue @Hina-Hussain  did you find any solution ?

**Comment by Hina-Hussain** [comment]
@AshishInnovantes no I did not. According to Apple documentation, they did not provide API to access the DateTime in iOS devices. So the developer of this plugin did not implement functionalities for iOS devices. For android, it's working fine.
For further information refer to this link: [https://developer.apple.com/forums/thread/7047](url)

**Comment by IvoBiaus** [comment]
That's 6 years old, they still dont provide this?
