### ISSUE TITLE
The plugin `datetime_setting` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by juangongora1** [fuadarradhi/datetime_setting#3]
Could you please migrate the plugin to v2 embedding?

**Comment by AshishInnovantes** [comment]
same here.

**Comment by jrmessias** [comment]
I have created a pull request

Check https://github.com/jrmessias/datetime_setting, is updated

**Comment by fuadarradhi** [comment]
thanks @jrmessias
