### ISSUE TITLE
DatetimeSettingPlugin.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by imaduddinmd** [fuadarradhi/datetime_setting#5]
Hey, Thanks for providing this package.

Lately, I have been seeing this warning in the logs whenever I run my app. I am not sure how long this warning been showing for but I noticed it fairly recently.

![image](https://github.com/fuadarradhi/datetime_setting/assets/99390744/9839d98c-d225-45ce-8868-a7f327df1beb)

**Comment by fuadarradhi** [comment]
thanks for that @imaduddinmd
